### ISSUE TITLE
Eye Of Rhianne 2 crashes on startup

### ISSUE THREAD

**Issue by amolokruo** [Liech/Yathsou#1]
I don't know whether this project is still being continued, but Eye Of Rhianne 2 crashes when I try to start it. the GL window opens for half a second and then disappears. I have made a units subfolder in the data folder and inserted the units into there, but it still crashes. Eye Of Rhianne 1 works fine though.

**Comment by amolokruo** [comment]
Looks like the issue was me not copying all gamedata .scds into the data folder and extracting them. This fixed it for me.

**Comment by Liech** [comment]
Yeah, i propably should add some error guidance here. Nice to see someone caring. Will upload new binaries soon. Holiday is about to start :D
